guestBook/urls.py
from django.urls import path, re_path, include
from .views import index, message_post, message_table

app_name = 'guestBook'

urlpatterns = [
    re_path(r'^$', index, name="index"),
    re_path(r'^add_message', message_post, name='add_message'),
    re_path(r'^result_table', message_table, name='result_table'),
]

lab_1/urls.py
from django.urls import re_path
from .views import index

# kadang kalo diacak acak juga boleh sangad


# url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

lab_2/urls.py
from django.urls import path, re_path
from .views import index

# url for app, add your URL Configuration

urlpatterns = [
    path(r'^$', index, name='index'),
    re_path(r'^$', index, name='index'),

]

lab_2_addon/urls.py
from django.urls import path, re_path
from .views import index

# url for app, add your URL Configuration

urlpatterns = [
    re_path(r'^$', index, name='index'),
]

midTest/urls.py
from django.urls import path, re_path
from .views import index

# url for app, add your URL Configuration

urlpatterns = [
    re_path(r'^$', index, name='index'),
]

my_experience/urls.py
from django.urls import path, re_path
from .views import index

# url for app, add your URL Configuration

urlpatterns = [
    re_path(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_1.views import index as index_lab1
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^lab-2-addon/', include('lab_2_addon.urls')),
    re_path(r'^my_experience/', include('my_experience.urls')),
    re_path(r'^$', index_lab1, name='index'),
    re_path(r'^midTest/', include('midTest.urls')),
    re_path(r'^guestBook/', include('guestBook.urls')),


]

urlpatterns += staticfiles_urlpatterns()

guestBook/models.py
from django.db import models
from datetime import datetime


class Message(models.Model):
    name = models.CharField(max_length=27)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(
        default=datetime.now(tz=None))

    def __str__(self):
        return self.message

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

lab_2_addon/models.py
from django.db import models

# Create your models here.

midTest/models.py
from django.db import models

# Create your models here.

my_experience/models.py
from django.db import models

# Create your models here.

guestBook/forms.py
from django import forms


class Message_Form(forms.Form):
    error_messages = {'required': 'Tolong isi input ini',
                      'invalid': 'Isi input dengan email', }
    attrs = {
        # 'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27,
                           widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(
        required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(
        widget=forms.Textarea(attrs=attrs), required=True)

guestBook/views.py
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message
from django.shortcuts import render
...


def index(request):
    response = {}
    html = 'index2.html'
    response['message_form'] = Message_Form
    return render(request, html, response)


def message_post(request):
    response = {}
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):

        if request.POST['name'] != "":
            response['name'] = request.POST['name']
        else:
            response['name'] = "Anonymous"

        if request.POST['email'] != "":
            response['email'] = request.POST['email']
        else:
            response['email'] = "Anonymous"

        response['message'] = request.POST['message']
        message = Message(
            name=response['name'],
            email=response['email'],
            message=response['message'])
        message.save()
        html = 'form_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/guestBook')


def message_table(request):
    response = {}
    message = Message.objects.all()
    # for i in message:
    #     i.created_date_time
    response['message'] = message
    html = 'tables.html'
    return render(request, html, response)

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'muhammat lio pratama'  # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
curr_month = int(datetime.now().strftime("%m"))
curr_day = int(datetime.now().strftime("%d"))
# TODO Implement this, format (Year, Month, Date)
birth_date = date(2001, 8, 22)
npm = 3141582622  # TODO Implement this
# Create your views here.


def index(request):
    response = {
        'page_name': 'Pengenalan diri Ajardia Beling',
        'name': mhs_name,
        'age': hitung_umur(birth_date.year, birth_date.month, birth_date.day),
        'npm': npm,
        'tempat_lahir': 'Jambi',
        'tanggal_lahir': birth_date.day,
        'bulan_lahir': tentukan_bulan(birth_date.month),
        'tahun_lahir': birth_date.year,
        'umur': hitung_umur(birth_date.year, birth_date.month, birth_date.day),
    }
    return render(request, 'profil2.html', response)


def hitung_umur(birth_year, birth_month, birth_day):
    # return curr_year - birth_year if birth_year <= curr_year else 0
    umur = curr_year - birth_year
    if curr_month - birth_month >= 0:
        if curr_day - birth_day >= 0:
            umur = umur
        else:
            return umur - 1
    else:
        return umur - 1
    return umur


def tentukan_bulan(birth_month):
    return {
        1: 'januari',
        2: 'februari',
        3: 'maret',
        4: 'april',
        5: 'mei',
        6: 'juni',
        7: 'juli',
        8: 'agustus',
        9: 'september',
        10: 'oktober',
        11: 'november',
        12: 'desember',
    }.get(birth_month, 'bulan not found')

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

# TODO Implement
# Create a content paragraph for your landing page:
landing_page_content = 'hahaha'


def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

lab_2_addon/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date
# Create a list of biodata that you wanna show on webpage:
# [{'subject' : 'Name', 'value' : 'Igor'},{{'subject' : 'Birth Date', 'value' : '11 August 1970'},{{'subject' : 'Sex', 'value' : 'Male'}
# TODO Implement
bio_dict = [{'subject': 'Name', 'value': mhs_name},
            {'subject': 'Birth Date',
             'value': birth_date.strftime('%d %B %Y')},
            {'subject': 'Sex', 'value': ''}]


def index(request):
    response = {}
    return render(request, 'description_lab2addon.html', response)

midTest/views.py
from django.shortcuts import render

# Create your views here.


def index(request):

    response = {
        'nama': 'muhammatliopratama'
    }
    return render(request, 'index.html', response)

my_experience/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    response = {
        'nama': 'LIO',
    }
    return render(request, 'my_experience.html', response)

guestBook/templates/form_result.html
{% extends "layout/base.html" %}
{% block title %} Pesan dari {{ name }} {% endblock %}
{% block content %}

<textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;- {{name}} by {{ email }} </textarea>
{% endblock %}

{% block footer %} <p> &copy; {{name}} </p> {% endblock %}

guestBook/templates/index2.html
{% extends 'layout/base.html' %}
{% block title %} silahkan tulis pesan anda disini{% endblock %}
{% block content %}
<section name="form">
    <h2>Send Message</h2>
    <form id="form" method="POST" action="{% url 'guestBook:add_message'  %}">
        {% csrf_token %}
        {{ message_form }} <br> <button type="submit" class="btn btn-default">Submit</button>
    </form>

    <!-- <form action="#" method="post">
        <label for="id_nama">Nama: </label>
        <input type="text" name="id_nama" name="nama">
    </form>

    <a href="{% url 'guestBook:result_table'%}">perlihatkan hasil</a> -->

</section>
{%endblock%}

guestBook/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
{%load static%}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {%endblock%}</title>
    <link rel="stylesheet" href="{% static 'src/base.css' %}">
    <link rel="stylesheet" href="{% static 'src/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'src/content.css' %}">
    <link rel="stylesheet" href="{% static 'src/footer.css' %}">

</head>

<body>
    {% include '../partials/header.html' %}
    {%block content%} {%endblock%}
    {% include '../partials/footer.html' %}


</body>

</html>

guestBook/templates/partials/footer.html
{%block footer%}
<div class="footer">
    <h3>&copy; Muhammat Lio Pratama - 2019</h3>
</div>
{%endblock%}

guestBook/templates/partials/header.html
{% block navbar%}
<div class="navbar">
    <ul>
        <li><a href="{%url 'guestBook:add_message' %}"> Buat Pesan</a></li>
        <li><a href="{% url 'guestBook:result_table' %}">Lihat Pesan</a></li>
    </ul>
</div>
{% endblock %}

guestBook/templates/tables.html
{% extends "layout/base.html" %}
{%load l10n%}
{% block title %} Kumpulan Pesan {% endblock %}
{% block content %}
<!-- Populate semua isi pesan dari model -->
<div class="table">
    <table class="table">
        <thead>
            <th>Nama</th>
            <th>Email</th>
            <th>Pesan</th>
            <th>Dibuat Pada</th>
        </thead>
        <tbody>
            <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
            {% for i in message %}
            {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
            <tr class="warning">{% else %}
            <tr class="success">
                {% endif %}
                <td> {{i.name}} </td>
                <td> {{i.email}} </td>
                <td> {{i.message}} </td>
                <td> {{i.created_date.time }} </td>
            </tr> {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>
</head>

<body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
    <article> saya lahir pada tanggal {{ tanggal_lahir}} {{bulan_lahir}} {{tahun_lahir  }}</article>
</body>

</html>

lab_1/templates/profil2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta http-equiv="X-UA-Compatible" content="ie=edge" />
	<title>{{ page_name }}</title>
	<link rel="stylesheet" href='{% static "src/profil2.css"%}' />

</head>

<body>
	<div class="gambar"></div>
	<div class="nama">Muhammat Lio Pratama <br>
		<a href="my_experience">Klik Disini bujank</a></div>
	<div class="barBawah">
		<div class="dataDiri">
			<h2>Data Diri</h2>
			<p>
				Tempat Dan Tanggal Lahir : {{ tempat_lahir }}, {{ tanggal_lahir }}
				{{ bulan_lahir }} {{ tahun_lahir }} (umur sekarang {{ umur }})
			</p>
			<p>Pendidikan : Calon Mahasiswa Telkom University</p>
			<p>
				Harapan : Biar bisa menambah ilmu dan dapat bertemu orang - orang baru
				serta dapat menjadi manusia yang bermanfaat
			</p>
			<p>Motto : MUNTUN BERCANDA!1!1!</p>
			<h1>
				APA APAAN MAKSUD ANDA MELIHAT INI!! PADAHAL OVERFLOWNYA SUDAH DI
				HIDDEN
			</h1>
		</div>
	</div>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

lab_2_addon/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

midTest/templates/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<title>MID TEST PROJECT BELING.ID</title>
		<link rel="stylesheet" href="../static/css/base.css" />
	</head>

	<body>
		<div class="headingBar">
			<ul>
				<li>HOME</li>
				<a href="#profile">
					<li>PROFILE</li>
				</a>
				<a href="#experienceSkill"><li>RESUME</li></a>
				<a href="#portfolio"><li>PORTFOLIO</li></a>
			</ul>
		</div>
		<div class="cover">
			<h1>𝙃𝘼𝙄, 𝙎𝘼𝙔𝘼 𝙇𝙄𝙊</h1>
			<p>Seorang programmer muda</p>
			<p>#Beling2019</p>
		</div>
		<div class="video">
			<video autoplay muted loop>
				<source src="../static/mp4/1.mp4" />
			</video>
		</div>

		<!-- todo  1. Menu Proﬁle, berisi: nama, deskripsi diri, email, dan sosial media  -->
		<!-- todo  2. Menu Resume, berisi: latar belakang pendidikan, pengalaman pekerjaan dan organisasi, kepanitiaan dan prestasi, serta bahasa pemrograman+framework dan organisasi -->
		<!-- todo  3. Menu portofolio, berisi screenshot/link ke karya-karya yang sudah kamu buat selama ini -->

		<div class="content">
			<a name="profile">
				<div class="profile">
					<h1>profil</h1>
					<div class="foto"></div>
					<p>
						HALO, Perkenalkan Nama Saya muhammat lio pratama. Seorang Pemogram
						web yang sudah mengenal web programming sejak kelas 2 sma. dalam
						program kelas online belajar programming (beling) ini saya harap
						saya mendapatkan ilmu mengenai pemograman django serta dapat
						mengenal lebih banyak orang yang lebih berpengalaman dari pada saya.
						sekian terimakasih
					</p>
				</div>
			</a>

			<div class="data"></div>
		</div>
		<div class="slash exeption"></div>

		<div class="pendidikan">
			<h1>Latar Pendidikan</h1>

			<!-- <p>berikut adalah latar pendidikan saya</p> -->
			<div class="satuanPendidikan">
				<h1>SD ISLAM AL - FALAH</h1>
				<h2>2006 - 2013</h2>
				<br />
				<p>
					Jl. Sultan Thaha No.58-B, Legok, Kec. Telanaipura, Kota Jambi, Jambi
					36112
				</p>
			</div>
			<div class="satuanPendidikan">
				<h1>MTS 2 KOTA JAMBI</h1>
				<h2>2013 - 2016</h2>
				<br />
				<p>
					Jl. Adityawarman No.05, The Hok, Kec. Jambi Sel., Kota Jambi, Jambi
					36125
				</p>
			</div>
			<div class="satuanPendidikan">
				<h1>MAN INSAN CENDEKIA JAMBI</h1>
				<h2>2016 - 2019</h2>
				<br />
				<p>
					Jl. Lintas Jambi- Muaro Bulian KM. 21, Pijoan, Kec. Jambi Luar Kota,
					Kota Jambi, Jambi 36657
				</p>
			</div>
			<div class="satuanPendidikan">
				<h1>TELKOM UNIVERSITY (TEKNIK KOMPUTER)</h1>
				<h2>2019 - sekarang</h2>
				<br />
				<p>
					Jl. Telekomunikasi Jl. Terusan Buah Batu No.01, Sukapura, Kec.
					Dayeuhkolot, Kota Bandung, Jawa Barat 40257
				</p>
			</div>
		</div>

		<div class="slash"></div>
		<a name="experienceSkill">
			<div class="pengalaman">
				<h1>Daftar Pengalaman</h1>
				<div class="satuanPengalaman">
					<h1>Juara 3 Lomba Matematika SLTP</h1>
					<p>
						IAIN SULTAN THAHA SYARIFUDDIN JAMBI
					</p>
					<h2>2016</h2>
				</div>
				<div class="satuanPengalaman">
					<h1>Ketua Tim Olimpiade Komputer</h1>
					<p>MAN INSAN CENDEKIA JAMBI</p>
					<h2>2018 - 2019</h2>
				</div>
				<div class="satuanPengalaman">
					<h1>Ketua TIM Komisi Pemilihan OSIM & MPS</h1>
					<p>MAN INSAN CENDEKIA JAMBI</p>
					<h2>2018</h2>
				</div>
			</div>
		</a>
		<div class="slash"></div>

		<div class="master">
			<h1>Skill Pemograman</h1>
			<div class="satuanMaster">
				<img src="../static/img/htmlLogo.png" alt="INI GAMBAR HTML 5!" />
				<div class="barMaster">
					<div class="progressbar" style="width: 85%;">85%</div>
				</div>
			</div>
			<div class="satuanMaster">
				<img src="../static/img/CSS3.svg" alt="INI LOGO CSS 3!" />
				<div class="barMaster">
					<div class="progressbar" style="width: 70%">70%</div>
				</div>
				<div></div>
			</div>
			<div class="satuanMaster">
				<img src="../static/img/javascriptLogo.svg" alt="" />
				<div class="barMaster">
					<div class="progressbar" style="width: 70%">70%</div>
				</div>
			</div>
			<div class="satuanMaster">
				<img src="../static/img/1280px-JQuery_logo_text.svg.png" alt="" />
				<div class="barMaster">
					<div class="progressbar" style="width: 60%">60%</div>
				</div>
			</div>
			<div class="satuanMaster">
				<img src="../static/img/phpLogo.svg" alt="" />
				<div class="barMaster">
					<div class="progressbar" style="width: 70%">70%</div>
				</div>
			</div>
			<div class="satuanMaster">
				<img src="../static/img/django-icon-0.svg" alt="" />
				<div class="barMaster">
					<div class="progressbar" style="width: 30%">30%</div>
				</div>
			</div>
		</div>
		<div class="slash"></div>
		<a name="portfolio">
			<div class="portfolio">
				<h1>Portfolio</h1>
				<div class="tempatPortfolio">
					<img src="../static/img/LOGIN.png" alt="" />
				</div>
				<div class="tempatPortfolio">
					<img src="../static/img/OSIM.png" alt="" />
				</div>
				<div class="tempatPortfolio">
					<img src="../static/img/MPS.png" alt="" />
				</div>
			</div>
		</a>
		<div class="copyright">
			<h3>Muhammat Lio Pratama © 2019</h3>
		</div>
	</body>
</html>

sumber 

my_experience/templates/my_experience.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href='{% static "src/my_experience.css"%}' />
    <link rel="stylesheet" href="../static/src/my_experience.css" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Oswald|Roboto&display=swap" rel="stylesheet" />
    <!-- TODO pasang nama document menggunakan data dari views.py -->
    <title>Document</title>
</head>

<body>
    <div class="navbar">
        <ul>
            <li class="first active" onclick="">home</li>
            <li class="second">experience</li>
            <li class="third">education</li>
            <li class="fourth">project</li>
            <li class="fifth">skills</li>
        </ul>
    </div>
    <div class="fotoUtama">
        <div class="gambar"></div>
        <div class="tampilanNama">
            Halo Nama Saya <br />
            {{ nama }}!
        </div>
    </div>
    <div class="tampilanData">
        <div class="data">
            <h1 class="biodataH1">BIODATA</h1>
            <p class="namaLengkap">Nama Lengkap : Muhammat Lio Pratama</p>
            <p class="tempatTanggalLahir">TTL: Jambi, 22 Agustus 2001(sekarang masih 17 hehe: )</p>
            <p class="harapan">Harapan : Biar bisa menambah ilmu dan dapat bertemu orang - orang baru serta dapat
                menjadi manusia yang bermanfaat</p>
            <p class="motto">Motto: Perlakukanlah orang lain sebagaimana engkau ingin diberlakukan</p>
        </div>
    </div>
</body>
<script src="{% static 'src/jquery.min.js' %}"></script>
<script src="{% static 'src/my_experience.js' %}"></script>
<script src="../static/src/jquery.min.js"></script>
<script src="../static/src/my_experience.js"></script>



</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}